# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goke < Formula
  desc ""
  homepage "https://github.com/dugajean/homebrew-goke"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dugajean/goke/releases/download/0.2.3/goke_0.2.3_Darwin_x86_64.tar.gz"
      sha256 "ce71adeee77240c0ad75231f436451b4c1bb91e6f47e848696812877779aa745"

      def install
        bin.install "goke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dugajean/goke/releases/download/0.2.3/goke_0.2.3_Darwin_arm64.tar.gz"
      sha256 "67369eea910c7145b98d27a404c370dd38daecb7a4ad34a2de2594dd981126fc"

      def install
        bin.install "goke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dugajean/goke/releases/download/0.2.3/goke_0.2.3_Linux_x86_64.tar.gz"
      sha256 "d9a6ea1d337a0e8991fd6367e0a3fcf2b53c53cb3d9c4c759afd4e12b13df132"

      def install
        bin.install "goke"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dugajean/goke/releases/download/0.2.3/goke_0.2.3_Linux_arm64.tar.gz"
      sha256 "126a3d8ea5488872207f23544a106a711a6fc56de52a01b6f16f233e78b76d8f"

      def install
        bin.install "goke"
      end
    end
  end
end
