# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goke < Formula
  desc ""
  homepage "https://github.com/dugajean/homebrew-goke"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dugajean/goke/releases/download/0.2.4/goke_0.2.4_Darwin_x86_64.tar.gz"
      sha256 "6dfcabaf4e3f2f960b80cba32aa490a4b160568253c7dd00cd32470df0168573"

      def install
        bin.install "goke"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dugajean/goke/releases/download/0.2.4/goke_0.2.4_Darwin_arm64.tar.gz"
      sha256 "bc47a03e739497657f98599b39490d6363e5ed8299e3faece488cf4694fab051"

      def install
        bin.install "goke"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dugajean/goke/releases/download/0.2.4/goke_0.2.4_Linux_arm64.tar.gz"
      sha256 "34ae556b07931faf9531b0037fd1546c62064897dd17c80c29e629e6c01c905c"

      def install
        bin.install "goke"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dugajean/goke/releases/download/0.2.4/goke_0.2.4_Linux_x86_64.tar.gz"
      sha256 "2cb378316d4ca56c82d40ca9735cdfb0309ddcbb94afb8f254df76251e9bee7b"

      def install
        bin.install "goke"
      end
    end
  end
end
